### ISSUE TITLE
IOS real device paytbas not working when I clicked on button nothing happens

### ISSUE THREAD

**Issue by devendra456** [paytabscom/paytabs-ios-library-sample#69]
2021-12-28 09:25:44.843544+0300 Runner[2217:1450158] [VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: FileSystemException: Cannot open file, path = '/var/mobile/Containers/Data/Application/D7F276D9-07DF-4171-84C9-2BAA1946982B/Documentslogo.png' (OS Error: Operation not permitted, errno = 1)
#0      _File.open.<anonymous closure> (dart:io/file_impl.dart:356:9)
#1      _rootRunUnary (dart:async/zone.dart:1436:47)
<asynchronous suspension>
#2      FlutterPaytabsBridge.handleImagePath (package:flutter_paytabs_bridge/flutter_paytabs_bridge.dart:106:13)
<asynchronous suspension>
#3      FlutterPaytabsBridge.startCardPayment (package:flutter_paytabs_bridge/flutter_paytabs_bridge.dart:96:47)
<asynchronous suspension>

**Comment by MuhamedAdly** [comment]
Hi @devendra456,
The issue is fixed in the latest version, you could check now.
